# Урок 3. Массивы

- Списки (Массиаы)
- Кортежи
- Множества
- Словари

## 1. Особенности работы с массивами. Базовые типы данных.

#### Пример 1. Удаление элемента списка во время его итерирования

In [1]:
list_1 = [1, 2, 3, 4]
list_2 = [1, 2, 3, 4]
list_3 = [1, 2, 3, 4]
list_4 = [1, 2, 3, 4]

In [2]:
# вариант 1
for i, item in enumerate(list_1):
    del item

print(list_1)

[1, 2, 3, 4]


In [3]:
# вариант 2
for i, item in enumerate(list_2):
    list_2.remove(item)
print(list_2)

[2, 4]


In [3]:
# вариант 3
for i, item in enumerate(list_2):
    list_3.pop(i)
print(list_3)

[2, 4]


In [4]:
for i, item, in enumerate(list_4[:]):
    list_4.remove(item)
print(list_4)

[]


#### Пример 2. Крестики-нолики,  где X побеждает с первой попытки

In [9]:
from pprint import pprint

row = [''] * 3
board = [row] * 3
board[0][0] = 'X'

print(board) 

[['X', '', ''], ['X', '', ''], ['X', '', '']]


In [11]:
board = [[''] * 3 for _ in range(3)]
board[0][0] = 'X'

print(board)

[['X', '', ''], ['', '', ''], ['', '', '']]


#### Пример 3. Те же операнды, но другая история

In [12]:
a = [1, 2, 3, 4]
b = a
a = a + [5, 6, 7]

print(a, b)

[1, 2, 3, 4, 5, 6, 7] [1, 2, 3, 4]


In [18]:
a = [1, 2, 3, 4]
b = a
a += [5, 6, 7]
print(a, b)

[1, 2, 3, 4, 5, 6, 7] [1, 2, 3, 4, 5, 6, 7]


#### Игла в стоге сена

In [19]:
t = ('one', 'two')  # кортеж
for i in t:
    print(i)

one
two


In [20]:
t = ('one')
for i in t:
    print(i)

o
n
e


In [23]:
t = ('one',)
for i in t:
    print(i)

one


#### Пример 5. Сохранить только уникальные значения

In [4]:
lst = [1, 5, 6, 1, 5, 2, 4, 5, 1, 6, 5]
lst = list(set(lst))
lst

[1, 2, 4, 5, 6]

#### Пример 6. Ключ словаря - изменяемый объект

In [6]:
set_x = {1, 2, 3}
lst_x = [1, 4, 9]

In [7]:
dict_x = {set_x: lst_x}

TypeError: unhashable type: 'set'

In [9]:
dict_x = {frozenset(set_x): lst_x}
dict_y = {tuple(lst_x): set_x}

print(dict_x)
print(dict_y)

{frozenset({1, 2, 3}): [1, 4, 9]}
{(1, 4, 9): {1, 2, 3}}


## 2. Алгоритмы обработки массивов. Часть 1.

#### Задача. Двоичный (бинарный) поиск

In [10]:
def bin_search(array: list, value: int) -> int:
    """ Бинарный поиск """
    left, right = 0, len(array) - 1
    pos = len(array) // 2

    while array[pos] != value and left <= right:
        if value > array[pos]:
            left = pos + 1
        else:
            right = pos - 1
        pos = (left + right) // 2

    return -1 if left > right else pos

In [15]:
import random

a = [random.randint(0, 1000) for _ in range(100)]
a.sort()
print(a)

n = int(input('\nКакой элемент найти: '))
print(bin_search(a, n))

[17, 23, 23, 24, 33, 42, 55, 72, 83, 108, 127, 129, 129, 130, 133, 139, 141, 142, 151, 155, 177, 184, 216, 219, 233, 239, 277, 284, 300, 310, 315, 323, 345, 350, 377, 380, 385, 389, 408, 439, 454, 461, 484, 500, 505, 514, 520, 522, 525, 532, 535, 556, 561, 563, 578, 583, 583, 605, 612, 638, 646, 657, 657, 674, 674, 676, 680, 680, 698, 701, 731, 737, 748, 750, 759, 770, 772, 784, 804, 809, 824, 825, 847, 850, 851, 857, 864, 878, 887, 888, 904, 912, 914, 922, 923, 923, 925, 927, 949, 956]

Какой элемент найти: 698
68


##  3. Алгоритмы обработки массивов. Часть 2.

#### Задача 1. Разложить положительные и отрицательные числа по разным массивам

In [23]:
import random

array = [random.randint(-100, 100) for _ in range(20)]
# print(array)

In [24]:
arr_bellow, arr_lager = [], []

for item in array:  
    if item > 0:
        arr_lager.append(item)
    else:
        arr_bellow.append(item)

print(f'arr_bellow {arr_bellow}')
print(f'arr_lager {arr_lager}')

arr_bellow [-94, -87, -58, -80, -65, -83, -16, -79, -40, -59]
arr_lager [64, 68, 61, 75, 61, 23, 91, 43, 69, 76]


#### Задача 2. Вставка элемента в прозвольное место массива

In [26]:
import random


array = [random.randint(-100, 100) for _ in range(20)]

num = int(input('Введите целое число для вставки: '))
pos = int(input('На какую позицию вставить число: '))

array.append(None)  # добавить в конец массива пустое значение
i = len(array) - 1

while i > pos:
    array[i], array[i - 1] = array[i - 1], array[i]
    i -= 1
array[pos] = num

# array.insert(pos, num)

print(array)

Введите целое число для вставки: 45
На какую позицию вставить число: 3
[62, 79, -34, 45, -63, 3, -8, -29, 81, -53, -89, -22, -58, -30, 7, -95, 23, -1, -59, -6, -85]


In [50]:
array_new = array[:pos] + [num] + array[pos:]
# но этот метод требует в 2 раза больше памяти

# 4. Алгоритмы обработки массивов. Часть 3.

#### Что такое матрица?

In [32]:
import random
import numpy as np

matrix = [[random.randint(1, 10) for _ in range(5)] for _ in range(7)]
np.array(matrix)

array([[ 7,  2,  5,  8,  1],
       [ 7,  8,  2,  6,  5],
       [ 8,  9,  4,  9, 10],
       [ 5,  7,  9, 10,  7],
       [ 5,  5,  7,  2,  5],
       [ 1,  4,  7,  4, 10],
       [10,  8, 10,  6,  5]])

#### Задача 1. Посчитать сумму строк и столбцов матрицы

In [46]:
sum_column = [0] * len(matrix[0])

for line in matrix:
    sum_line = 0
    for i, item in enumerate(line):
        sum_line += item
        sum_column[i] += item
        print(f'{item:>3}', end='')
    print(f'  | {sum_line}')
print('-' * (len(matrix) * 3))

for s in sum_column:
    print(f'{s:>3}', end='')

  7  2  5  8  1  | 23
  7  8  2  6  5  | 28
  8  9  4  9 10  | 40
  5  7  9 10  7  | 38
  5  5  7  2  5  | 24
  1  4  7  4 10  | 26
 10  8 10  6  5  | 39
---------------------
 43 43 44 45 43

In [41]:
print(f'суммы строк = {np.array(matrix).sum(axis=0)}')
print(f'суммы столбцов = {np.array(matrix).sum(axis=1)}')

суммы строк = [43 43 44 45 43]
суммы столбцов = [23 28 40 38 24 26 39]


#### Задача 2. Обмен значений главной и побочной диагоналей квадратной матрицы

In [48]:
import random

size = 5
matrix = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
print(np.array(matrix))

for i in range(size):
    for j in range(size):
        if i == j:
            spam = matrix[i][j]
            matrix[i][j] = matrix[i][size - 1 - j]
            matrix[i][size - 1 - j] = spam
print('-' * 20)
for line in matrix:
    for item in line:
        print(f'{item:>3}', end='')
    print()

[[ 6  3 10  1  9]
 [ 5  9  8  2  5]
 [ 5  2  9  1  7]
 [ 9  1  9 10  6]
 [ 5  7  1  4  2]]
--------------------
  9  3 10  1  6
  5  2  8  9  5
  5  2  9  1  7
  9 10  9  1  6
  2  7  1  4  5


## 5. Работа с ассоциативными массивами (`dict`)

#### Задача. Пользователь вводит количество предприятий, названия, плановую и фактическую прибыль каждого предприятия. Вычислить процент выполнения плана и вывести данные с предарительной фальтацией

In [1]:
k = int(input('Введите количество предприятий: '))
enterprises = {}

for i in range(1, k + 1): 
    name = input('Введите название предприятия: ')
    enterprises[name] = [float(input('План: ')), float(input('Факт: '))]
    enterprises[name].append(enterprises[name][1] / enterprises[name][0])

print(f'Фактиеская прибыль больше 10, но план не выполнен')
for key, value in enterprises.items():
    if value[1] > 10 and value[2] < 1:
        print(
            f'Предприятие {key} заработало {value[1]}, что составило {value[2]*100:.2f}%'
        )

Введите количество предприятий:  4
Введите название предприятия:  a
План:  12
Факт:  11
Введите название предприятия:  b
План:  16
Факт:  9
Введите название предприятия:  c
План:  13
Факт:  11
Введите название предприятия:  d
План:  11
Факт:  13


Фактиеская прибыль больше 10, но план не выполнен
Предприятие a заработало 11.0, что составило 91.666667%
Предприятие c заработало 11.0, что составило 84.615385%
